COMMON_CONFIGS_SRC := AnalogicSensorConfig.cpp \
    Config.cpp \
    DynamixelConfig.cpp \
    JoypadConfig.cpp \
    KinectConfig.cpp \
    LowLevelConfig.cpp \
    MoveSchedulerConfig.cpp \
    MoveSchedulerSensorsConfig.cpp \
    PinsConfig.cpp \
    PwmConfig.cpp \
    ServosConfig.cpp 

